### ISSUE TITLE
Status reboot required bleibt bestehen

### ISSUE THREAD

**Issue by 90er** [HenriWahl/checkmk-agent-plugin-yum#12]
Hallo aus Bayern,

wir nutzen das genannte Plugin nun eine Weile in der aktuellen Version in Verbindung mit Check_MK Enterprise Edition in aktueller Version 1.5.0p11 und früher.

Anfang der Woche hat das Plugin erkannt, das Updates für mehrere Hosts ausstehen. Nachdem ich diese auf den Zielsystemen (Hosts) installiert habe, hat der Status auf "WARN - reboot required" gewechselt. Ich habe den Neustart der Hosts durchgeführt (Uptime 2 Tage, 11 Stunden). Der Status des Checks bleibt jedoch so bestehen. Woran kann das liegen? Das Plugin wird alle 24 Stunden (Ordner 86400) ausgeführt.

Ausgabe Agent:
<<<yum>>>
yes
0

Ausgabe Server (cmk -d <Host>):
<<<yum>>>
yes
0

Ausgabe Server (cmk -D <Host>|grep yum)
yum     None     {'reboot_req': 1}     YUM

Danke

**Comment by HenriWahl** [comment]
Hallo,

das hatte ich auch schon vereinzelt - die Ursache habe ich noch nicht herausgefunden. "Gelöst" hatte ich es dann immer mit `rm -f /var/lib/check_mk_agent/cache/yum_*.cache`.

**Comment by HenriWahl** [comment]
Should be fixed with above PR.
