### ISSUE TITLE
All packages are up to date unter Debian

### ISSUE THREAD

**Issue by 90er** [HenriWahl/checkmk-agent-plugin-yum#13]
Hallo aus Bayern,

wenn man das Plugin auf einen Host unter Debian verteilt liefert dieser "OK - All packages are up to date" zurück. Es wäre hier sinnvoller, dass ein Hinweis ausgegeben wird, dass es sich nicht um ein apt System wie Debian oder Ubuntu handelt oder einfach kein Output zurück kommt.

Ausgabe am Ziel Host (check-mk-agent)
<<<apt:sep(0)>>>
No updates pending for installation
<<<yum>>>
no
0

Danke

**Comment by HenriWahl** [comment]
Öhm... hier handelt es sich aber um YUM?

**Comment by 90er** [comment]
> 
> 
> Öhm... hier handelt es sich aber um YUM?

Entschuldigung, ich weiß nicht, warum der Inhalt nicht korrekt kopiert wurde.
Ich wollte zeigen, dass apt und yum als Plugins auf dem Debian 9.6 System laufen.

```
<<<apt:sep(0)>>>
No updates pending for installation
<<<yum>>>
no
0
```

**Comment by HenriWahl** [comment]
OK... aber warum?
