### ISSUE TITLE
Yum Plugin not compatible with Bakery

### ISSUE THREAD

**Issue by Lucadrio** [HenriWahl/checkmk-agent-plugin-yum#2]
Hello,

your Check_MK Agent Plugin is not compatible with the Agent Bakery in the Check_MK Version: Enterprise 1.2.8p15

**Comment by HenriWahl** [comment]
Thanks for the hint - any idea how to make it compatible? :-)

**Comment by Lucadrio** [comment]
No sorry. :-(
I'm pretty new to the whole "Check_MK World". I only received the Tip to let you know about the Problem, so you can solve it.

**Comment by lgbff** [comment]
Hi @all,

i send a pull request in the coming days...

**Comment by HenriWahl** [comment]
@lgbff good news... :-)

**Comment by lgbff** [comment]
#3

**Comment by HenriWahl** [comment]
Fixed by https://github.com/HenriWahl/checkmk-agent-plugin-yum/pull/3
