### ISSUE TITLE
add new mkp file

### ISSUE THREAD

**Issue by pdcemulator** [HenriWahl/checkmk-agent-plugin-yum#24]
the latest mkp file (yum-2.0.9.mkp) in this repo is not compatible with agent bakery from 1.6 release. But you have working files in this repo, please yust add them to mkp file :-)

**Comment by HenriWahl** [comment]
Hi,
as far as I remember I created this file with Checkmk 1.6. Can you provide any error message?

**Comment by pdcemulator** [comment]
The Bakery cannot build the agent.
The file agents/bakery/yum in the mkp package is not the latest from this repo.

**Comment by HenriWahl** [comment]
Finally yum-2.0.10.mkp uploaded - please check if it works for you.
