### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by SjamonDaal** [HenriWahl/checkmk-agent-plugin-yum#26]
Please add python3 support for new 2020 distros.

**Comment by thorian93** [comment]
I know there can be no demands towards @HenriWahl, as he does this in his free time, but can anyone - maybe Henri himself - tell if or when a Checkmk 2.0 compatible version might be available? Or at least point to an alternative?

**Comment by thorian93** [comment]
See #32 for more information on the state of this repo.
