### ISSUE TITLE
Problem with RHEL/CentOS8 and dnf (yum-cache)

### ISSUE THREAD

**Issue by FJerusalem** [HenriWahl/checkmk-agent-plugin-yum#27]
To fix replace
YUM_CURRENT="$(ls -lR /var/cache/yum/)"
with
YUM_CURRENT="$(ls -lR /var/cache/yum/ || ls -lR /var/cache/dnf/)"
in yum-plugin.

**Comment by HenriWahl** [comment]
Thanks - please check fixed .mkp-file.

**Comment by FJerusalem** [comment]
works fine. thanks a lot!
