### ISSUE TITLE
Error in Checkmk 2.0 bakery

### ISSUE THREAD

**Issue by rickbaran** [HenriWahl/checkmk-agent-plugin-yum#32]
Upgraded to version 2.0 and now get error message when you try to apply changes.

`Error in agent bakery plugin file yum: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (, line 16)`

Removed package, applied to get errors to go away but after reinstallation of package get the same error message.

**Comment by thorian93** [comment]
I think this is due to Python 3 support as requested in #26.

**Comment by rickbaran** [comment]
I'm speculating that as well. This issue but a big is wrench our deployment of CMK. I am assuming that if we remove the package and bake the agents that it will remove the yum plugin from all of the deployed agents? I would contribute if I could but programing is not my thing.

**Comment by thorian93** [comment]
Well yes, you will use the check altogether.

I am no programmer myself, but it is too bad, that this is an blocking upgrades and on top Henri is short on time as he said in another issue. Maybe another python dev stumbles through here.

**Comment by HenriWahl** [comment]
Hi there,
adding to missing time there is as well no Checkmk 2.0 instance in reach to check what is going on with the plugin, so I hope someone might help out there.

**Comment by thorian93** [comment]
I posted a feature idea in the [Checkmk forum](https://forum.checkmk.com/t/include-yum-plugin-in-checkmk/24790), maybe they can support or pick up the great work from this repository.
