### ISSUE TITLE
missing square brackets

### ISSUE THREAD

**Issue by m3rlinux** [HenriWahl/checkmk-agent-plugin-yum#39]
Hi,
perhaps is better using this form on line 29
if [ ! -e "$YUM_CACHE_FILE" ] && [ ! -f "$YUM_CACHE_FILE" ]
 becouse running a script it throws the error of "missig bracket"

https://github.com/HenriWahl/checkmk-agent-plugin-yum/blob/2ee2eb6660970a36141b01be1f788d5175427dae/agents/plugins/yum#L29

**Comment by HenriWahl** [comment]
Do you get an error?

**Comment by m3rlinux** [comment]
Yep, see belove
![image](https://user-images.githubusercontent.com/16387701/124388345-cf165900-dce2-11eb-9e71-979df472c2ef.png)

**Comment by HenriWahl** [comment]
What shell you you run it on?

**Comment by HenriWahl** [comment]
no news...
