### ISSUE TITLE
Cannot modify check parameters

### ISSUE THREAD

**Issue by simon-mueller** [HenriWahl/checkmk-agent-plugin-yum#4]
Hi,

I installed the latest yum.mkp and i cannot modify the check parameters for this check.

I want to change it, so that available packages don't give a warning
and a required reboot is not critical but only a warning.

However, when I create a new rule in manual checks for yum I am not able to change any parameters.

![grafik](https://cloud.githubusercontent.com/assets/3966858/23663045/b8ce5680-0351-11e7-814d-7c1b6517ae7b.png)

Info:
-----
Check_MK RE 1.2.8p18
yum-2.0.4.mkp

**Comment by lgbff** [comment]
Hi,

this Plugin is not configurable ;-)
The rule is only for activate manual check.

hth Karsten
