### ISSUE TITLE
No yum plugin after 2.3

### ISSUE THREAD

**Issue by lionking62** [HenriWahl/checkmk-agent-plugin-yum#45]
After upgrading yum mkp to 2.3.0 and baking agents, the yum plugin are not there anymore.

**Comment by schoekek** [comment]
the same on my environment...  
while omd update to version p9 this message generatet:
ERROR: Failed to transform rule: (Ruleset: static_checks:yum, Folder: , Rule: 0, Value: ('yum', None, None): Dictionary.transform_value() got a non-dict: None

**Comment by HenriWahl** [comment]
What Checkmk version do you use?

**Comment by lionking62** [comment]
I use enterprise 2.0p9

**Comment by schoekek** [comment]
i the same...

**Comment by HenriWahl** [comment]
> the same on my environment...
> while omd update to version p9 this message generatet:
> ERROR: Failed to transform rule: (Ruleset: static_checks:yum, Folder: , Rule: 0, Value: ('yum', None, None): Dictionary.transform_value() got a non-dict: None

From which version of Checkmk and yum plugin did you upgrade?

**Comment by HenriWahl** [comment]
Looks like https://github.com/HenriWahl/checkmk-agent-plugin-yum/blob/master/lib/check_mk/base/cee/plugins/bakery/yum.py works different now?

**Comment by HenriWahl** [comment]
At least I can confirm that the `yum` snippet is missing in the baked agent.

@schoekek are you able to find any difference between the 1.6 and 2.0 bakery?

**Comment by schoekek** [comment]
@HenriWahl pls make this:
`mv local/lib/python3/cmk/check_mk/base/cee/plugins/bakery/yum.py local/lib/python3/cmk/base/cee/plugins/bakery/`

**Comment by HenriWahl** [comment]
@schoekek any idea how?

**Comment by schoekek** [comment]
just move the file, I went after that ..

**Comment by HenriWahl** [comment]
Please check latest release v2.3.1 https://github.com/HenriWahl/checkmk-agent-plugin-yum/releases/tag/v2.3.1

**Comment by HenriWahl** [comment]
Nothing new...
