### ISSUE TITLE
Error when trying to bake Agents with this yum plugin enabled.

### ISSUE THREAD

**Issue by DreFraNorge** [HenriWahl/checkmk-agent-plugin-yum#46]
I get the following error when try to bake Agents with the yum plugin enabled.
I am running on CEE 2.0.0p9.
Any idea what it can be?

===============================
Exception: Error running automation call bake-agents (exit code 2), error: 
Error creating agent for checkmk2.xxxxx.xx: Error creating agents: Error creating b611afddc96d4415/linux_deb agent for checkmk2.xxxxx.xx: Error in bakery plugin "yum": name 'shutil' is not defined

Traceback (most recent call last):
  File "<string>", line 10, in bake_yum
NameError: name 'shutil' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/monitoring/lib/python3/cmk/base/cee/bakery/agent_bakery.py", line 426, in _execute_pre_17_bakery_plugin
    bake_func(**func_args)
  File "<string>", line 15, in bake_yum
NameError: name 'shutil' is not defined
.
.

More information can be found in ~/var/log/web.log

===============================

**Comment by Jon1760** [comment]
Version 2.3.1 resolved this issue for me.  It uses the new Check_MK API for agent plugins.

**Comment by DreFraNorge** [comment]
Thanks for your answer.
I have updated to 2.3.1 and now it works.
