### ISSUE TITLE
Executing yum with --no-plugins disables priorities plugin 

### ISSUE THREAD

**Issue by spenneb** [HenriWahl/checkmk-agent-plugin-yum#48]
Hi,
the yum agent plugin calls yum with the option --no-plugins which normally is fine. But I am using the priorities plugin to ensure updates from specific repositories. Disabling this plugin detects updates which are disabled. This should be a configurable option. 
Maybe using --disable-plugin=[list] to make this configurable.

**Comment by HenriWahl** [comment]
AFAIK there is no way to send options to the agent as the server gets its raw output as it is.

**Comment by HenriWahl** [comment]
@spenneb you are right, this way it should work.
I don't have the resources to include this but pull requests are welcome.
