### ISSUE TITLE
Unable to load ENV variables

### ISSUE THREAD

**Issue by righter83** [HenriWahl/checkmk-agent-plugin-yum#49]
Hi 

I installed the latest version 2.3.2
On every CentOS Machine I got the following error

`Unable to load ENV variables`

This variable is nowhere declared, should it be somewhere?

**Comment by timothestoifl24** [comment]
Check [https://docs.checkmk.com/latest/en/agent_linux.html#manual](url)

**Comment by HenriWahl** [comment]
Can this be closed?

**Comment by timothestoifl24** [comment]
@HenriWahl Since this Issue has nothing to do with this Plug-In, you could close it.
