### ISSUE TITLE
Check_MK Agent Plugin is not compatible v1.4.0

### ISSUE THREAD

**Issue by Lucadrio** [HenriWahl/checkmk-agent-plugin-yum#5]
**New Version - old Problem!**

your Check_MK Agent Plugin is not compatible with the Agent Bakery in the Check_MK Version: Enterprise 1.4.0

**Error-Code**:

`Failed to bake the agents: Error creating agent for warhol: Error creating 13b9d226f1d928d3/linux_rpm agent for warhol: Error in bakery plugin "yum": global name 'local_agents_dir' is not defined

Traceback (most recent call last):
File "/omd/sites/nordakademie/share/check_mk/modules/agent_bakery.py", line 273, in execute_bakery_plugin
bakery_info[plugin_name]["bake_function"](opsys, conf, conf_dir, plugins_dir)
File "/omd/sites/nordakademie/local/share/check_mk/agents/bakery/yum", line 9, in bake_yum
shutil.copy2(local_agents_dir + "/plugins/yum", target_dir + "/yum")
NameError: global name 'local_agents_dir' is not defined
.. `
_--_
**Screenshot**:
![grafik](https://cloud.githubusercontent.com/assets/25505054/26639100/33271772-4624-11e7-941f-426ca80f7d06.png)

Cheers,
Luca

**Comment by HenriWahl** [comment]
I thought this was fixed for 1.2.8... well, as soon as I have a running 1.4.0 I will check this issue.

**Comment by lgbff** [comment]
I dont't have a 1.4 side...maybee in july ;-)

**Comment by HenriWahl** [comment]
But does it work on earlier versions than 1.4.0?

**Comment by Lucadrio** [comment]
Yes it worked on the 1.2.8 Version. But the newest update broke something.

**Comment by 230542** [comment]
Trivial change to get it working > 1.4.0
In the package, in agents/bakery/yum, replace in line 9:
-         shutil.copy2(local_agents_dir + "/plugins/yum", target_dir + "/yum")
with
+        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/yum", target_dir + "/yum")

As a temporary workaround, files in downloaded package can be edited - mkp is just a tar.gz archive.

**Comment by lgbff** [comment]
I have the confirmation from mk company.
This is only >= 1.4 compatible ;-(
@HenriWahl fix this alone?

**Comment by HenriWahl** [comment]
I'll check when back from vacations.

**Comment by HenriWahl** [comment]
fixed by commit 71152b09fb27935deb7214b46096a1a92e987380
