### ISSUE TITLE
MKP for 2.4.1

### ISSUE THREAD

**Issue by 47k** [HenriWahl/checkmk-agent-plugin-yum#54]
Can you please prepare a MKP for 2.4.1 as well :)

**Comment by HenriWahl** [comment]
What about https://github.com/HenriWahl/checkmk-agent-plugin-yum/releases/tag/untagged-6d9aefdfad757a2e2e1b ?

**Comment by schoekek** [comment]
under https://github.com/HenriWahl/checkmk-agent-plugin-yum/releases/tag/v2.4.1
no 2.4.1 mkp asset found.

**Comment by HenriWahl** [comment]
- - Thanks for insisting... release was still a draft. Now it works.
