### ISSUE TITLE
OpenVZ Kernel

### ISSUE THREAD

**Issue by chb1981** [HenriWahl/checkmk-agent-plugin-yum#6]
verification for reboot failed if you running a vzkernel

LINE 52:
LATEST_KERNEL=$(yum -q -C --noplugins list installed kernel | grep "\." | tail -n1 | awk '{print $2};')

yum list installed *kernel*
vzkernel.x86_64                                                     2.6.32-042stab123.9                                              @openvz-kernel-rhel6

**Comment by HenriWahl** [comment]
fixed by https://github.com/HenriWahl/checkmk-agent-plugin-yum/pull/7
