### ISSUE TITLE
current script reports incorrect numbers of security updates

### ISSUE THREAD

**Issue by swampdogmash** [HenriWahl/checkmk-agent-plugin-yum#62]
The yum command used takes longer than 10 seconds to run on many servers. The current agent plugin script only waits for 10 seconds (although it then runs for 25 seconds when doing the actual check with a similar command.) I've submitted a pull request https://github.com/HenriWahl/checkmk-agent-plugin-yum/pull/61 to update the plugin to wait for 25 seconds during the validation stage of the security updates check which seems to fix the issue - although I haven't got the knowledge to understand if this impacts anything to do with the overal timings of the scripts and any CheckMK specific timeouts (how long the script takes to run etc) as it extends the possible runtime by 15 seconds.

**Comment by HenriWahl** [comment]
@swampdogmash thanks, the new release is already available. :+1:
