### ISSUE TITLE
yum-2.4.4.mkp missing in v2.4.4 release

### ISSUE THREAD

**Issue by moschlar** [HenriWahl/checkmk-agent-plugin-yum#63]
I don't understand why, because according to Actions, it was successfully uploaded as a release artifact, but it nevertheless is missing...

https://github.com/HenriWahl/checkmk-agent-plugin-yum/releases/download/v2.4.4/yum-2.4.4.mkp

**Comment by HenriWahl** [comment]
@moschlar thanks for the hint - there was another v2.4.4 release being a draft which had the MKP. Looks like I was too fast creating the release, which came automatically by actions. Now all schould be fixed.
