### ISSUE TITLE
Problem with Version 1.4.0p15

### ISSUE THREAD

**Issue by Lucadrio** [HenriWahl/checkmk-agent-plugin-yum#8]
Hello,

It´s me again... the newest Check_MK Update (Enterprise 1.4.0p15) broke the yum-plugin again.

![grafik](https://user-images.githubusercontent.com/25505054/31444599-f17f35fc-ae9c-11e7-9c21-68dd37f7599e.png)

**Error Code:**
` Failed to bake the agents: Error creating agent for vangogh: Error creating cdc69d79930a0da8/linux_rpm agent for vangogh: Error in bakery plugin "yum": global name 'local_agents_dir' is not defined

Traceback (most recent call last):
File "/omd/sites/nordakademie/share/check_mk/modules/agent_bakery.py", line 274, in execute_bakery_plugin
bakery_info[plugin_name]["bake_function"](opsys, conf, conf_dir, plugins_dir)
File "/omd/sites/nordakademie/local/share/check_mk/agents/bakery/yum", line 9, in bake_yum
shutil.copy2(local_agents_dir + "/plugins/yum", target_dir + "/yum")
NameError: global name 'local_agents_dir' is not defined
..  `

Thanks for fixing in advance!

Cheers,
Luca

**Comment by HenriWahl** [comment]
Works even on the latest 1.5 release so I consider this to be ready to close.
