### ISSUE TITLE
versions 2.5.x + break monitoring on 2.2.0p31

### ISSUE THREAD

**Issue by Glowsome** [HenriWahl/checkmk-agent-plugin-yum#83]
**Environment:** CheckMK RAW 2.2.0p31 (recently upgraded from 2.1.0p46)

**Situation:** 
- uninstalled my previous 2.4.1 yum *mkp package to not block upgrade of CMK ( all went well)
- installed latest 2.5.1 *mkp package to be future-prepared

**Symptoms:** since this upgrade all yum checks are going into 'stale' mode on Check-MK server.

**Backtracking:**
Gradually removed, and re-added a lower version of the yum .mkp, and it seems that as soon as i drop below the 2.5.* version/threshold it starts working again.

Currently working with 2.4.2 without any issues.

So what has rudimentary change from 2.4.x -> 2.5.x and breaks the check in CMK 2.2.0p31 ?

- Glowsome

**Comment by HenriWahl** [comment]
@Glowsome sorry for the late reply - do you get some debug output?

**Comment by Glowsome** [comment]
> @Glowsome sorry for the late reply - do you get some debug output?

i'll have to repeat the process, but will post it here.

**Comment by Glowsome** [comment]
Here is a replay of what i just (re-)did ( from a working plugin 2.4.2)
```
OMD  su <mysitename>
mkp list  #to see the version (in my case 2.4.2)
mkp disable yum
mkp remove yum
mkp add yum-2.5.1.mkp
mkp enable yum
```
At this point all hosts (31) who use this plugin/package went to 'stale' 

After that i replaced the yum client plugin on one of the hosts to the match version with the installed .mkp (2.5.1)
- Extra info i have the client package in a subdir to only call it once every hour.

To get debug data i checked discovery (this is a RockyLinux 9 host):
`cmk --debug -vvII auth.mydomain.tld`
I can see the plugin is detected / service found.
I also see an entry in the information of the plugin:
`<<<yum:cached(1724608180,3600)>>> / Transition HostSectionParser -> HostSectionParser`

As i have the time i waited out a/the hour for the plugin to run again, to see if it smooths out itself, and to not force stuff (like deleting caches on purpose)

pre-rotation timestamp of cached files:
```
-rw-r--r-- 1 root root     2 Aug 25 20:34 yum_uptime.cache
-rw-r--r-- 1 root root    28 Aug 25 20:34 plugins_yum.cache
-rw-r--r-- 1 root root 20251 Aug 25 20:34 yum_update.cache
-rw-r--r-- 1 root root    18 Aug 25 20:34 yum_result.cache
```

After having waited over an hour, also looking at the timestamp on the cached files on the monitored host (to see if they rotated over) none of the hosts have recovered.
Cache files were rewritten (see timestamps below)
```
-rw-r--r-- 1 root root     7 Aug 25 21:34 yum_uptime.cache
-rw-r--r-- 1 root root    28 Aug 25 21:34 plugins_yum.cache
-rw-r--r-- 1 root root 20251 Aug 25 21:34 yum_update.cache
-rw-r--r-- 1 root root    18 Aug 25 21:34 yum_result.cache
```

Also when running debug on the server `cmk --debug -vvn auth.mydomain.tld | grep yum` i can see that the entry has been updated with a new timestamp:
`<<<yum:cached(1724614488,3600)>>> / Transition HostSectionParser -> HostSectionParser`

Still none of the 31 hosts is reporting in regarding YUM.

Is there anything in particular i can do to deliver you specifics regarding debug ?

- Glowsome

**Comment by Glowsome** [comment]
little addition, i bumped my CMK version to 2.20p32 since i opend this issue, so the above was performed on that version.

**Comment by swampdogmash** [comment]
You could try manually running the plugin (by adding a temporary variable at the beginning of the client yum plugin python file usually in /usr/lib/check_mk_agent/......)

ADD:

`$MK_VARDIR = " /var/lib/check_mk_agent/"  `  

or whatever you use as your vardir immediately after the !#/bin/bash first line.

This should allow you to see any errors that happen when the check is run manually on the console and potentially output something helpful for debug.

**Comment by Glowsome** [comment]
Sorry for the late response, had to deal with other stuff.

> Also: what version and flavour of monitored client OS are you running the plugin on?

i have multiple:
- SLES 15 SP5
- SLES 12 SP3 (for legacy applications)
- RockyLinux 9.x

**Comment by swampdogmash** [comment]
I'm not too familiar with Suse, could you please run the following on each of the flavours of OS and show the results please?

grep -oP '(?<=^VERSION_ID=").*(?=")' /etc/os-release | cut -d '.' -f 1

Starting to think it might be better if i check the version of YUM not the version of the OS (which seems obvious now I think about it)

**Comment by Glowsome** [comment]
> grep -oP '(?<=^VERSION_ID=").*(?=")' /etc/os-release | cut -d '.' -f 1
>
>In addition, does Suse not use Zypper and not yum? Or do you have a special setup? Are you actually running THIS yum plugin on SUSE - I don't understand how that would work.

You are right, i was just being daft here, as i just ran quickly thru my hosts and summed up all *.rpm style boxes.
So affected boxes are all RockyLinux 9.x
