### ISSUE TITLE
Question about when yum cache is updated

### ISSUE THREAD

**Issue by dgcurtis** [HenriWahl/checkmk-agent-plugin-yum#9]
I've installed the plugin and copied the yum agent to the clients.  It seems like 4-5 months ago, yum doesn't get run to update the cache.  It's happened on both my RHEL6 and RHEL7 servers.  I don't believe I've changed anything but maybe I'm misunderstanding how the yum cache gets updated.  Am I supposed to be using yum-cron with check only enabled or is the yum plugin supposed to run yum to update the yum cache?  Unless I run "yum check-update" manually, the yum plugin never reports that there are any updates.

Thanks

**Comment by HenriWahl** [comment]
Yes, the plugin does not care abut DOING the updates. A cronjob including

    yum check-update -q

does the trick.
